# Generated by Django 2.2.7 on 2019-12-01 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactrental',
            old_name='info_rental',
            new_name='information',
        ),
    ]
