# Generated by Django 2.2.7 on 2019-11-15 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20191113_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='home_id',
            field=models.IntegerField(default=0),
        ),
    ]
