# Generated by Django 2.2.7 on 2019-12-02 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('An agent/broker', 'An agent/broker'), ('Homebuyer/seller', 'Homebuyer/seller'), ('Other professionals', 'Other professionals')], max_length=100)),
                ('name', models.CharField(max_length=150)),
                ('information', models.TextField(blank=True)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=40)),
                ('ad_picture', models.ImageField(upload_to='pictures/%Y/%m/%d/')),
                ('card_title', models.CharField(default='', max_length=100)),
                ('card_text', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
