# Generated by Django 2.2.7 on 2019-11-17 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertise',
            name='card_text',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='advertise',
            name='card_title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
