# Generated by Django 2.2.7 on 2019-12-01 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0002_auto_20191117_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertise',
            name='email',
            field=models.EmailField(max_length=40),
        ),
    ]
