# Generated by Django 2.2.7 on 2019-12-02 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0003_auto_20191201_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertise',
            name='role',
            field=models.CharField(choices=[('An agent/broker', 'An agent/broker'), ('Homebuyer/seller', 'Homebuyer/seller'), ('Other professionals', 'Other professionals')], max_length=100),
        ),
    ]
