# Generated by Django 2.2.6 on 2019-10-29 04:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_title', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=100)),
                ('information', models.TextField(blank=True)),
                ('price', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.DecimalField(decimal_places=1, max_digits=2)),
                ('garage', models.IntegerField(default=0)),
                ('homesize', models.IntegerField()),
                ('landsize', models.DecimalField(decimal_places=1, max_digits=5)),
                ('top_photo', models.ImageField(upload_to='pictures/%Y/%m/%d/')),
                ('picture1', models.ImageField(blank=True, upload_to='pictures/%Y/%m/%d/')),
                ('picture2', models.ImageField(blank=True, upload_to='pictures/%Y/%m/%d/')),
                ('picture3', models.ImageField(blank=True, upload_to='pictures/%Y/%m/%d/')),
                ('picture4', models.ImageField(blank=True, upload_to='pictures/%Y/%m/%d/')),
                ('picture5', models.ImageField(blank=True, upload_to='pictures/%Y/%m/%d/')),
                ('picture6', models.ImageField(blank=True, upload_to='pictures/%Y/%m/%d/')),
                ('is_posted', models.BooleanField(default=True)),
                ('date_posted', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='agents.Agent')),
            ],
        ),
    ]
