# Generated by Django 2.2.7 on 2019-11-10 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0002_auto_20191110_0648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='agents.Agent'),
        ),
    ]
