# Generated by Django 2.2.7 on 2019-11-18 05:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0006_auto_20191118_0406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
