# Generated by Django 2.2.7 on 2019-11-18 05:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0007_auto_20191118_0511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='date_posted',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
