# Generated by Django 2.2.7 on 2019-11-18 05:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0008_auto_20191118_0512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='date_posted',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='is_posted',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
