# Generated by Django 2.2.7 on 2019-11-24 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0010_auto_20191124_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
